### ISSUE TITLE
For results maybe do a side by side plot and for table results try doing visualization with a plot. It's hard scrolling up and down to read it.

### ISSUE THREAD

**Issue by ericlee0920** [UBC-MDS/DSCI_522_group_31#55]

**Comment by yaz-saleh** [comment]
Group discussion notes:

- [ ] Adjust sizes of plots to lay them down side by side with the table (if possible and looks good)

**Comment by lephanthuymai** [comment]
Hi @ericlee0920 ,
My understanding is that there are 2 requirements for this task:

1.  Wrap figures inside paragraphs so that the reader does not need to scroll down to compare the results with the figures
2. Instead of tables, try visualizing them with charts when possible

Please confirm, thank you very much.

**Comment by lephanthuymai** [comment]
Regarding #2, after reading the report carefully, I think it is easier to review in the table format instead of charts as it is a standard format when we reviewing models and view classification report, hence no change is made regarding this point.

Regarding #1, I tried wrapping figures inside paragraphs, but it does not look better than arranging figures and tables side by side to reduce the need of scrolling up and down, so I've changed the report to work that way instead.

Please review the generated report again once the PR is merged to the main repo and let me know if you still see any issues.
